vrrp_script check_nginx {
    script "/etc/keepalived/check_nginx.sh"
    interval 2
    weight   -30
    fall     2
    rise     2
}

vrrp_instance VI_PROXY {
    state  BACKUP            # Este nodo inicia como BACKUP
    interface enp0s3
    virtual_router_id 52     # Mismo ID que el maestro
    priority 100             # Menor prioridad que el maestro (110)
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass ProxyHA2024
    }
    virtual_ipaddress {
        192.168.200.7/24
    }
    track_script { check_nginx }
}
